# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [4]:
# Load CSV 
df = pd.read_csv ("../output_data/weather_status.csv")

df

,city,latitude,longitude,max_temp,humidity,cloudiness,windspeed,country,date
0,Coruripe,-10.13,-36.18,82.00,57,19,12.06,BR,1609265448
1,George Town,5.41,100.34,81.00,83,20,3.36,MY,1609265449
2,Petropavlovsk-Kamchatskiy,53.05,158.65,6.80,71,93,6.71,RU,1609265450
3,Hilo,19.73,-155.09,69.80,60,1,6.93,US,1609265302
4,Cape Town,-33.93,18.42,71.01,64,20,16.11,ZA,1609265272
...,...,...,...,...,...,...,...,...,...
545,Lampa,-33.28,-70.90,86.00,39,0,17.22,CL,1609266139
546,Boffa,10.17,-14.03,83.35,66,1,9.46,GN,1609266141
547,Vardø,70.37,31.11,30.20,86,75,21.92,NO,1609266142
548,Twentynine Palms,34.14,-116.05,50.00,57,1,13.87,US,1609266143
549,Tarauacá,-8.16,-70.77,83.48,76,59,4.00,BR,1609266145

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [6]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)

In [9]:
df['humidity'].max()

100

In [14]:
# Store 'Lat' and 'Lng' into  locations 
locations = df[["latitude", "longitude"]]

df

# Create a poverty Heatmap layer
fig = gmaps.figure(center=[0,0], zoom_level=2)

heat_layer = gmaps.heatmap_layer(locations, weights=df['humidity'], 
                                 dissipating=False, max_intensity=80,
                                 point_radius = 2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [16]:
ideal_weather = df.loc[(df['max_temp'] >= 70) & (df['max_temp'] < 80) & (df['windspeed'] < 10) & (df['cloudiness'] < 10)]

ideal_weather

,city,latitude,longitude,max_temp,humidity,cloudiness,windspeed,country,date
14,Avarua,-21.21,-159.78,77.00,100,3,1.12,CK,1609265464
99,Kahului,20.89,-156.47,73.00,77,1,5.82,US,1609265570
118,Salalah,17.02,54.09,75.20,57,0,3.36,OM,1609265450
142,Aguié,13.51,7.78,74.61,20,4,6.98,NE,1609265627
196,Mundo Nuevo (Ojo de Agua),18.70,-95.50,72.37,67,0,2.75,MX,1609265696
231,Cabo San Lucas,22.89,-109.91,75.00,56,5,8.05,MX,1609265737
301,Zunil,14.78,-91.48,77.00,39,0,4.74,GT,1609265831
328,Arlit,18.74,7.39,71.96,19,4,7.70,NE,1609265866
339,Hambantota,6.12,81.12,77.02,82,4,7.83,LK,1609265880
399,Sokoto,13.06,5.24,77.95,18,0,8.10,NG,1609265957
467,Batticaloa,7.71,81.69,78.57,76,1,1.32,LK,1609265969

* Narrow down the DataFrame to find your ideal weather condition. For example:

  * A max temperature lower than 80 degrees but higher than 70.

  * Wind speed less than 10 mph.

  * Zero cloudiness.

  * Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure